"""add_llm_models_table

Revision ID: c472b1280b95
Revises: ef55233a9283
Create Date: 2026-01-12 21:35:58.728745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c472b1280b95'
down_revision: Union[str, None] = 'ef55233a9283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('max_tokens_limit', sa.Integer(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k_input_tokens', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cost_per_1k_output_tokens', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_llm_models_id'), 'llm_models', ['id'], unique=False)
    
    # Create default LLM models
    from datetime import datetime
    now = datetime.utcnow().isoformat()
    
    # Get OPENAI_API_KEY from environment or use placeholder
    import os
    openai_key = os.getenv('OPENAI_API_KEY', 'OPENAI_API_KEY_PLACEHOLDER')
    
    op.execute(f"""
        INSERT INTO llm_models (name, display_name, provider, api_key, api_base_url, 
                               max_tokens_limit, context_window, 
                               cost_per_1k_input_tokens, cost_per_1k_output_tokens,
                               is_active, is_default, created_at, updated_at)
        VALUES 
            ('gpt-4', 'GPT-4 (OpenAI)', 'openai', '{openai_key}', NULL, 
             4096, 8192, 0.03, 0.06, 1, 1, '{now}', '{now}'),
            ('gpt-3.5-turbo', 'GPT-3.5 Turbo (OpenAI)', 'openai', '{openai_key}', NULL,
             4096, 16385, 0.0015, 0.002, 1, 0, '{now}', '{now}'),
            ('claude-3-sonnet', 'Claude 3 Sonnet (Anthropic)', 'anthropic', '', NULL,
             4096, 200000, 0.003, 0.015, 0, 0, '{now}', '{now}')
    """)
    
    # Get default model ID
    default_model_id_result = op.get_bind().execute(
        sa.text("SELECT id FROM llm_models WHERE is_default = 1")
    )
    default_model_id = default_model_id_result.fetchone()[0]
    
    # Add llm_model_id column with server_default pointing to default model
    # Note: FK constraint will be created through batch operations due to SQLite limitations
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_model_id', sa.Integer(), nullable=False, server_default=str(default_model_id)))
        batch_op.create_foreign_key('fk_agents_llm_model', 'llm_models', ['llm_model_id'], ['id'], ondelete='RESTRICT')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.alter_column('agents', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('agents', 'llm_model_id')
    op.drop_index(op.f('ix_llm_models_id'), table_name='llm_models')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
