"""add_usage_tracking_and_free_limits

Revision ID: ef55233a9283
Revises: 10805613c4fc
Create Date: 2026-01-12 21:00:36.615678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef55233a9283'
down_revision: Union[str, None] = '10805613c4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_accounts', sa.Column('free_requests_used', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('billing_accounts', sa.Column('requests_used_current_period', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('billing_accounts', sa.Column('period_started_at', sa.DateTime(), nullable=True))
    op.add_column('billing_accounts', sa.Column('trial_started_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_prompt_versions_agent_active', table_name='prompt_versions')
    op.create_index(op.f('ix_prompt_versions_agent_id'), 'prompt_versions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.add_column('subscription_plans', sa.Column('free_requests_limit', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('subscription_plans', sa.Column('free_trial_days', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'free_trial_days')
    op.drop_column('subscription_plans', 'free_requests_limit')
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_agent_id'), table_name='prompt_versions')
    op.create_index('ix_prompt_versions_agent_active', 'prompt_versions', ['agent_id', 'is_active'], unique=False)
    op.drop_column('billing_accounts', 'trial_started_at')
    op.drop_column('billing_accounts', 'period_started_at')
    op.drop_column('billing_accounts', 'requests_used_current_period')
    op.drop_column('billing_accounts', 'free_requests_used')
    # ### end Alembic commands ###
